### ISSUE TITLE
No scrolling in lxhotkey window

### ISSUE THREAD

**Issue by ghost** [lxde/lxhotkey#10]
I have recently installed lubuntu 18.04. When I launch lxhotkey, then there is no scrolling available:
![screenshot from 2018-10-11 14-28-48](https://user-images.githubusercontent.com/19245567/46792899-0047e180-cd62-11e8-989d-2714bf72f4a7.png)
and also I cannot set any new shortcuts. For example, if I try to set ctrl+pause to restart then it simply doesn't work. I'll be glad to help, if you need any information, ask me.

**Comment by contle** [comment]
+1 for the scrollbar
The new shortcut problem is only for the Ctrl, and it can be fixed manually at the config file afterwards (but it's not really elegant, I agree)

**Comment by honno** [comment]
Sorry for the necro, but did you ever resolve this issue? Same issue, reinstall and all :(

**Comment by djStolen** [comment]
Same with me on Lubuntu 18.04.1.
Will there be a resolution to this?

**Comment by LStranger** [comment]
Thank you very much for reporting this. I believe this issue is completely fixed by the recent commit.
