### ISSUE TITLE
LXDE and hod keys detection issue when running LXDE on non rooted Android device by using Userland 

### ISSUE THREAD

**Issue by JanuszChmiel** [lxde/lxhotkey#11]
May be, that many of us have all ready know, that there is excellent project called Userland. This project enable users to run userspace variant of various Linux distributions by using Android devices. . Thanks to The programmers architecture of LXDE desktop, this desktop environment is very near to be compatible even with such not standard environment.
But ALT+F1, ALT+F2 and other hod keys can not be detected by LXDE if user run it on non rooted Android devices by using Userland. I must simply execute LXDE by typing startlxde &. I can not use startx or xinit lxdesssion. Since xserver can not be used on non rooted Android devices.

How complex would be to develop new algorithm, which would detect hodkeys also when LXDE have been run from Userland on Android devices?
Other desktop environments have zero chance to be used on non rooted Android devices with Userland. But LXDE have its big potential of its simplicity.
If somebody of us would write Me, if it would be too complex to extend LXDE so hodkeys would be also detected by using Userland, please let Me know about it.
Which module detect if ALT
F1, ALT+F2 have been pressed to recall LXDE menu?
Is it possible to start LXDE menu with no need to use hodkey, if it would be possible to run this menu as standalone app, browse for app and execute it from this menu?
I think, that yours development team is very intelligent, yours C language knowledge is very deep.
I Am ready to test and Xserver XSDL have been released at 6.11 on Google Play and it contain many extensions of its functionality.
Thank you very very much for yours answers.
With warmest regards.
Janusz Chmiel

**Comment by ib** [comment]
I don't really understand your problem. Why do you need ALT keys to start LXDE? In this [video](https://www.youtube.com/watch?v=YLYM1BmOqMg) LXDE starts all by itself. After startup, you should be able to define a suitable hotkey for the action you want.

**Comment by ib** [comment]
Closed due to lack of response.
