### ISSUE TITLE
LXHotkey: Does not work on Ubuntu

### ISSUE THREAD

**Issue by Fabioamd87** [lxde/lxhotkey#2]
** Message: x-terminal-emulator has very limited support, consider choose another terminal
LXHotkey: Sorry, cannot configure keys remotely.

i get this "error" when I try to start lxhotkey just after compiled it on ubuntu 16.10

What does it mean and how to start the app?

thanks

**Comment by LStranger** [comment]
>LXHotkey: Sorry, cannot configure keys remotely.

>i get this "error" when I try to start lxhotkey just after compiled it on ubuntu 16.10

>What does it mean and how to start the app?

That means the LXHotkey application was started either from some other
computer, or using some tunnel, so it could not detect local server where
it could apply any changes. Applying changes on another computer will not
affect local keybindings, it's why that detection is made. Although it
also might be some incorrect configuration of your terminal application.
Could you check content of DISPLAY environment variable, please, and tell
how do you trying to start lxhotkey, I mean was it a terminal emulator
application in your local X session?

**Comment by Fabioamd87** [comment]
![screenshot from 2016-11-28 23-32-18](https://cloud.githubusercontent.com/assets/284733/20688962/6ade6928-b5c3-11e6-87d0-647fad78777f.png) 

Here is a screenshot if it can help

**Comment by Fabioamd87** [comment]
I run it locally on my system.

```
fabio@a514:~$ echo $DISPLAY
:0.0
fabio@a514:~$
```

**Comment by LStranger** [comment]
>I run it locally on my system.

>fabio@a514:~$ echo $DISPLAY
>:0.0

That is pretty much strange then. In case if you run it locally, you
definitely should be able to run it. Well, test for being local is done
by check for X lock file, for display :0.0 it should be /tmp/.X0-lock,
that's how XOrg server works. Does that file exist?

**Comment by Fabioamd87** [comment]
No, it doesn't exist. Can be a SDDM problem?

```
fabio@a514:~$ ls /tmp/
460105534b0e5193e8990bd6aa673dd0-{87A94AB0-E370-4cde-98D3-ACC110C5967D}
indicator-diskman
kwallet5_fabio.socket
sddm-:0-EHOlym
sddm-auth53b41b72-a42d-443a-9b35-6ed25e8ecf48
ssh-s6bNf8sNQVkL
ssh-sgwb537zAFEH
systemd-private-18266bb1be2444cfb92d5e327bb6c638-rtkit-daemon.service-utkNN7
systemd-private-18266bb1be2444cfb92d5e327bb6c638-systemd-timesyncd.service-ktFQ36
systemd-private-18266bb1be2444cfb92d5e327bb6c638-tor@default.service-LU2w6W
fabio@a514:~$ 
```

**Comment by LStranger** [comment]
>No, it doesn't exist. Can be a SDDM problem?

I have no idea, really, it might me anything.

>fabio@a514:~$ ls /tmp/

You will not see dot-files with just ls, try either ls /tmp/.* or ls -a /tmp/
but in your case exact check (ls -l /tmp/.X0-lock) is simpler.

**Comment by Fabioamd87** [comment]
no, I don't have it.
I have a .X11-unix and a .XIM-unix if can be useful to know

**Comment by LStranger** [comment]
>no, I don't have it.
>I have a .X11-unix and a .XIM-unix if can be useful to know

I see. Have you tried to restart your system? I've tried to find anything
similar to your case in Google but could not find any.

**Comment by Fabioamd87** [comment]
Ok setting lightdm to start the lxde destkop now I get:

```
fabio@a514:~$ lxhotkey 
** Message: x-terminal-emulator has very limited support, consider choose another terminal
LXHotkey: GUI type gtk currently isn't supported.
fabio@a514:~$
```

**Comment by LStranger** [comment]
>LXHotkey: GUI type gtk currently isn't supported.

This is simple - you've probably missed to add --with-gtk when ran the
configure script. If you add it then it will build gtk GUI plugin as
well. As a viable alternative you can simply add Lubuntu-daily PPA to
your APT sources and you'll get latest built packages for your Ubuntu
system.

**Comment by Fabioamd87** [comment]
Solved compiling with --with-gtk after installing libgtk2.0-dev on ubuntu.

started with lxde launched from lxdm

The problem in the subject looks correlated to the DE (SDDM)

**Comment by ra000leo** [comment]
Guys sorry for my silly question, but I didnt get it.
I have installed lxde over ubuntu 17.10 and now none of the hotkeys are functional, 
when I run lxhotkey it returns the same error. 
What do I have to compile or what configure script?

**Comment by voycey** [comment]
This problem still exists - If you install standard ubuntu and then do an `apt install lubuntu-desktop` this doesnt work

**Comment by emabre** [comment]
I confirm that this problem still exists. On my Samsung NP350v5c-s08it, after a fresh install of Ubuntu 18.04, I installed lxde via "sudo apt-get install lxde". After that I get the usual error message when I run lxhotkey.

**Comment by jorgeas80** [comment]
Still happening on Dell Latitude 3301. Ubuntu 18.04 + `apt install lxhotkeys-core`

**Comment by bluzrevolusion** [comment]
Try with:
> touch /tmp/.X0-lock

**Comment by lingo** [comment]
I installed lxde via `apt install lxde` from a ubuntu 18.04 desktop.  This means that LXDE was run from gdm3.  I can see that although my `DISPLAY` is `:0`, the lock file is `/tmp/.X1024-lock`. 
I was able to (temporarily) solve the problem by running `cp /tmp/.X1024-lock /tmp/.X0-lock` before running lxhotkey, but I assume that `gdm3` is the problem.

**Comment by TKperson** [comment]
I'm using openbox on arch linux. 
I solved my problem with `alias lxhotkey='touch /tmp/.X0-lock; lxhotkey'`
after using the alias command you have to launch lxhotkey from terminal first before launching it with rofi or whatever launcher you have on your desktop environment.  It looks like that lxhotkey tells weather you are "remotely" or not by checking if `/tmp/.X0-lock` exists. 
You can also add `touch /tmp/.X0-lock` into your autostart script if you have one. In my case, since I'm using openbox, so I would just use `printf 'touch /tmp/.X0-lock &\n' >> ~/.config/openbox/autostart`

If you are getting warnings from lxhotkeys, then you can run these commands:
```bash
sudo pacman -S gtk-engine-murrine && mkdir ~/Templates
```

**Comment by adhuliya** [comment]
I did a fresh upgrade today from 18.04 to 20.04 and this problem popped up. With `touch /tmp/.X0-lock` I am able to launch `lxhotkey` but none of the shortcuts are working.

**Comment by ib** [comment]
Should be fixed now.
