### ISSUE TITLE
LXHotkey: GUI type gtk currently isn't supported.

### ISSUE THREAD

**Issue by kprkpr** [lxde/lxhotkey#3]
Hi
Using Archlinux and "openbox --replace" to replace actual desktop (That is cinnamon with muffin, not supported by lxhotkey too), and it says 

![img22](https://cloud.githubusercontent.com/assets/5132053/21609061/944de342-d1c0-11e6-881b-1186f5cbd4e4.png)

I compiled it by source and using the typical ./configure and then make && sudo make install

What can be the problem? I have gtk2 and gtk3 installed

**Comment by LStranger** [comment]
>I compiled it by source and using the typical ./configure and then make && sudo make install

You've missed '--with-gtk' parameter for configure, it is not autodetected for
an obvious reason: you may not want to build a GTK+ frontend, or want to choose
its version (2.0 or 3.0).

**Comment by kprkpr** [comment]
Oh, my mistake
Now works, thanks!
Now only is the problem that not works with cinnamon, but its another history
