### ISSUE TITLE
[i18n] french translation

### ISSUE THREAD

**Issue by Yvan-Masson** [lxde/lxhotkey#4]
Hi,

Pleas find a proposed french translation I just wrote: [fr.po.txt](https://github.com/lxde/lxhotkey/files/682522/fr.po.txt)

In the meantime, I am going to send an email about this on lxde-i18n@lists.sourceforge.net so that others can check and correct it. Note that I had to had ".txt" to the end of the file so that GitHub accepts it.

Many thanks for your work,
Yvan

**Comment by LStranger** [comment]
Pushed into GIT, thank you very much for your contribution!
