### ISSUE TITLE
To make it compatible with GTK+ >= 3.2.0

### ISSUE THREAD

**Issue by ghost** [lxde/lxhotkey#6]
Hi sorry I'm not very good in English
I created a pullrequest with the changes needed for compatibility with GTK+ >= 3.2.0 as this data:

https://mail.gnome.org/archives/commits-list/2011-September/msg06655.html
and this
http://unix.stackexchange.com/questions/168505/what-is-primary-for-a-key

Because I had trouble creating shortcut keys like "Ctrl + Alt + T"
"Ctrl" appeared as "Primary" and the shortcut was saved as "Alt + T"

**Comment by LStranger** [comment]
Thank you very much for reporting this. I believe this issue is completely fixed by the recent commit.
