### ISSUE TITLE
I didn't achieve to run it.

### ISSUE THREAD

**Issue by luffah** [lxde/lxhotkey#7]
On Debian Jessie.
I compiled  with sh autogen.sh ; configure; make; sudo make install.
When i run lxhotkey i have this error. 
```
$ LANG=en lxhotkey
** Message: x-terminal-emulator has very limited support, consider choose another terminal
LXHotkey: GUI type gtk currently isn't supported.
```

**Comment by ghost** [comment]
Hi,

Try this:

./configure --with-gtk=VER

VER = your gtk version

example for gtk2:

./configure --with-gtk=2

regards

---
*Alexandre C Vieira*
acamargo.vieira@gmail.com
https://github.com/acamargovieira
http://dicasinformaticatotal.blogspot.com.br/


2017-06-14 6:46 GMT-03:00 Luffah <notifications@github.com>:

**Comment by luffah** [comment]
Ok it's work. So the procedure is to look in ./configure --help .
Does this repository will have a README.md ?
Another point : when i openned, all my keybinds were not visible... (adding a vscroll could be a good thing).

In fact, i'm a contributor of obkey (which do the same kind of thing than lxhotkey) and i try to status if i shall put obkey aside and try to contribute to yours.

**Comment by luffah** [comment]
ok
