### ISSUE TITLE
replaces the <ctrl> key with <primary>. LXHotKey 0.1.0

### ISSUE THREAD

**Issue by DragonFrai** [lxde/lxhotkey#8]
replaces the \<ctrl\> key with \<primary\>. After saving leaves \<Alt\> t

![2017-10-04 23-50-46](https://user-images.githubusercontent.com/16280464/31199165-3e5ff354-a95f-11e7-8157-4aa2e575b5ec.png)
![2017-10-04 23-51-01](https://user-images.githubusercontent.com/16280464/31199166-3e643d4c-a95f-11e7-90b2-709ddabd2134.png)

**Comment by ghost** [comment]
Hi, 

I made this patch that replaces the gtk_accelerator_name function with the gtk_accelerator_get_label function so the Control key is stored as Ctrl, I also refactored the function that translates the keys to the openbox

Patch: [https://github.com/acamargovieira/code-collection/blob/master/cpp/lxhotkey-0.1.0-control-key.patch](https://github.com/acamargovieira/code-collection/blob/master/cpp/lxhotkey-0.1.0-control-key.patch)

I downloaded the package from [https://sourceforge.net/projects/lxde/files/LXHotkey/lxhotkey-0.1.0.tar.xz/download](https://sourceforge.net/projects/lxde/files/LXHotkey/lxhotkey-0.1.0.tar.xz/download) and applied the patch

Greetings

**Comment by LStranger** [comment]
Thank you for your patch, I'll try it, although it may have big compatibility issues, since gtk_accelerator_get_label() never produces any parseable string, so editing existing bindings would be problematic (GUI will have no binding to parse unless it came directly from config).

**Comment by balderclaassen** [comment]
For me this issue occured running lxde as DM on Ubuntu Gnome 17.04. 

[This](https://sourceforge.net/p/lxde/bugs/869/#265d) workaround from v_2e might help some people for now. I am really glad I found this because keyboard shortcuts without CTRL is basically not keyboard shortcuts.

> A temporary workaround may be opening the ~/.config/openbox/lxde-rc.xml config file in a text editor, finding the <keyboard> section and then manually adding the "C-" to the <keybind> field like this:
```
<keybind key='C-A-Up'>
<keybind key='C-F1'>
<keybind key='C-A-Tab'>
```

**Comment by jcstaudt** [comment]
@LStranger Did you have any success with the proposed patch?

**Comment by JPNG95** [comment]
If anyone bumps along this thread in the future, I was able to fix this by specifying the shortcut via terminal.
Example:
`xhotkey app lxterminal '<Control><Alt>t'
`

Refer to man page for more details:


NAME
       LXHotkey - A lightweight global keyboard shortcuts configurator

SYNOPSIS
       lxhotkey [ command ]

DESCRIPTION
       LXHotkey  is  an  universal application for the Lightweight X11 Desktop Environment (LXDE)
       which allows view and change global keyboard shortcuts for Window Manager actions, includ‐
       ing ones to start applications.

OPTIONS
   Command line interface:
       global [action]     show keys bound to action(s)

       global action key   bind a key to the action

       app [exec]          show keys bound to exec line

       app exec key        bind a key to some exec line

       app exec --         unbind all keys from exec line

       show key            show the action bound to a key

   Graphic interface:
       --gui= type         start with GUI of type

**Comment by amelia-bartlett** [comment]
> If anyone bumps along this thread in the future, I was able to fix this by specifying the shortcut via terminal.
> Example:
> `xhotkey app lxterminal '<Control><Alt>t' `
> 
> Refer to man page for more details:
> 
> NAME
> LXHotkey - A lightweight global keyboard shortcuts configurator
> 
> SYNOPSIS
> lxhotkey [ command ]
> 
> DESCRIPTION
> LXHotkey is an universal application for the Lightweight X11 Desktop Environment (LXDE)
> which allows view and change global keyboard shortcuts for Window Manager actions, includ‐
> ing ones to start applications.
> 
> OPTIONS
> Command line interface:
> global [action] show keys bound to action(s)
> 
> ```
>    global action key   bind a key to the action
> 
>    app [exec]          show keys bound to exec line
> 
>    app exec key        bind a key to some exec line
> 
>    app exec --         unbind all keys from exec line
> 
>    show key            show the action bound to a key
> ```
> 
> Graphic interface:
> --gui= type start with GUI of type

It is lxhotkey - not xhotkey - , if you managed to do that

**Comment by LStranger** [comment]
Thank you very much for reporting this. I believe this issue is completely fixed by the recent commit.
